# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorts',
            old_name='outgoingurl',
            new_name='outgoingurl1',
        ),
        migrations.AddField(
            model_name='shorts',
            name='outgoingurl2',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
