# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0002_auto_20160516_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorts',
            name='outgoingurl2',
        ),
    ]
